import {IPost} from './IPost';

export interface IFeed {
    /**
     * Contains the id which is generated by the database
     */
    id?: number;

    /**
     * Contains the user specific name to this feed
     */
    name?: string;

    /**
     * Contains the URL to the feed
     */
    url?: string;

    /**
     * Contains the URL to the website of the feed
     */
    website?: string;

    /**
     * Timestamp when the feed got the last update
     */
    lastBuildDate?: Date;

    /**
     * Contains all posts for this feed
     */
    posts: IPost[];
}
