export interface IPost {
    /**
     * Contains the id which is generated by the database
     */
    id?: number;

    /**
     * Contains the title of the post
     */
    title?: string;

    /**
     * Contains the description of the post
     */
    description: string;

    /**
     * Contains the URl to the post
     */
    link?: string;

    /**
     * Contains the timestamp when the post was published
     */
    publishDate: Date;

    /**
     * Contains the E-Mail adress of the author
     */
    author?: string;

    /**
     * Contains all categories to which this post belongs to
     */
    categories?: string[];
}
